checks:
    php: true
    
build:
    tests:
        override: 
            - 
                command: './vendor/bin/phpcs ./src/domain.php --report=checkstyle --report-file=cs-data '
                analysis:
                    file: 'cs-data'
                    format: 'php-cs-checkstyle'
